language: python
python:
  - "3.8"
cache: pip
env:
  global:
    - secure: ONTbNMryuzMjRrcFVEBWMyqkGAhec9FR0NMdhrK+MaYo4ebGY87yWsV2m/5uNtqO3RAeH9yu+bWuMET/vH17HQEXBzl98uzM1A1j0Be/ywvXVdq/IJ69Y1pdYzvGRkVhWEAduS7+7BRKEHc0pCZjQxYzglgD9NerkNYH3l4Q2gWcL+rsw2zwpdoEsxPAlyYv6zSdPG/K2WXosRGP82fIlJ82JSLKxps1/XTrcpJ0oNLDHniasGjoAJcx6IOPXibqvWCQntL9GfRcds+U7StPaKMQ7UIZ/GT9U6wk7SCHuYV3QylQvyBLNW3qU64jFsviPJ6MFoVHMka6HIDDINAGDIxC9F4AsOMgaAMBb8AnCffm9ZG/u0ph1vW3EOmsarj0ZXFhIPLjFxNcBMl8esi4gghqD5wHlzW0djnntBOTEqIaB2X+HN1sj5y/2+Cq9t1VL05Sifu8DWiAGmwf9wbX8+p/UuulYatkvCNQ4zY+YDA339n/3u0YIh/LM/N7vynZREuKstEeczWBkczkL5+Mz00KFr9SMWhPVYbLZUP4YuHL7Spd8dz87sq/CyQFXzoZUk22OQZzD3ujltuSWUS4L3lqRDBNM8fvCj5KrOA3IcOjjk9aehBKeyh4FPBkst+vAmrb4z4jv8FhjaFgaAWIGuxlP1UxnMxUlZSXalW5SXo=
    - secure: tv++kck3GwHBNtlxqFgjNKJ6OzmexaHPzCJ/riItOOE6+Yd07quE5r0PZY+7ME/mMcfPwL5BlXufhaz//XDPhdRhtGBeH8vZCP/uBfAd3elGpQIkV5JEJhqibXMhjxuCQI4OGikUFCpNbGa7FyScb8ywE372upoDCUwcv7AUfkvl/T5jCnb9yQYf7E2edV2MpKUF68FBVuenJZGbYz06QrO44qRQISvDZUaxD1ccegUDYWkCJoEUA453KfmF7+lk9aZsJz1MIBlY7/EuV7IrzNmNfAK3UrbROM4JF3ovZbG6mPhDN0vx9f9jxQFPrB7QuXPtbgBqISXCTG7GzOautp6mz4EJsGhi7Tn+WoVx0j3xK0hHUmdomjhjxjGyTYzIitsy7cYR0G03WCsmm1fR2QnWEse3MTEx2ykXJ8Fk4LzmOx/P8HQr6l62wuV9r0Xi/Jg6BydJJ0IiBOp0WSuM4BAe2EvsG0AuyXfc8RZfdPzd9AKds2fzshpqn+1BTASQ6jlFiD/lUrjuO2ATXfEVMlr2idUpv8j3EvYOxX+hhVclirFpWQYQg5/eL5n2P4pfSozB2jtOCW8WfWgbrEmvQUy5Mk7YS8W6pnxeWSPlCMSvRlrAZDoGDf7AUsO5gf7mB9PsKMR0lobR1pvwq7LOyU3OGacsTvJjvl5W5en8xno=
install:
  - pip install poetry
  - poetry install
script:
  - poetry run black --check .
  - poetry run flake8 **/*.py
  - poetry run bandit -r -ll **/*.py
  - poetry run bandit -r numiner
  - poetry run pytest --cov --verbose
deploy:
  provider: script
  script: poetry publish --build --username=$PYPI_USER --password=$PYPI_PASSWORD
  on:
    tags: true
after_success:
  - coveralls
